### ISSUE TITLE
Dio error

### ISSUE THREAD

**Issue by berkersen** [cozvtieg9/weblatesdk#11]
Hi mate,

I'm trying to integrate weblate_sdk to my project but getting the following error:

`
Unhandled Exception: 'package:dio/src/options.dart': Failed assertion: line 108 pos 16: 'baseUrl.isEmpty || Uri.parse(baseUrl).host.isNotEmpty': is not true.
E/flutter (16539): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (16539): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
`

Here is the project: https://translate.codeberg.org/projects/keyoxide/

It might also be something that I wrongly configured in the project. I'd really appreciate if you could have a look.
Thanks in advance.

**Comment by cozvtieg9** [comment]
Hi. Can you show your SDK initialization code?

**Comment by berkersen** [comment]
Sure.

`
await WebLateSdk.initialize(
    token: 'API Access Token',
    host: 'Keyoxide Mobile App',
    projectName: 'Keyoxide',
    componentName: 'Keyoxide (mobile)',
    defaultLanguage: 'en',
  );
`

**Comment by cozvtieg9** [comment]
In `host` you need set your Weblate host url. It should be `https://translate.codeberg.org` in your case.

**Comment by berkersen** [comment]
Thanks mate. The error is gone but I'm getting this now:

`
I/flutter (15518): WebLate SDK: Api Error.: 404: Not found.
I/flutter (15518): WebLate SDK: Initialized Successfully.: Got remote translations [] for Keyoxide (mobile)
`
And when I try to use it with context.localizedValueOf("view_profile"), it shows the key instead of the translation value.

**Comment by cozvtieg9** [comment]
`token: 'API Access Token'`
I believe there real token in your code, not just "API Access Token"?  
**If not, here the steps how you can get the token:**
You can generate it in Project Api settings.
 - On your project page press "Manage" -> Api Access
 - Then onto Create a project token enter token name and press create.
 - You'll see message "Token created. Please save it now, as it won't be displayed again:", so press copy token and paste in initialization code.
 - Then press edit token and change restrictions to Languages only. (like on screenshot)
<img width="415" alt="image" src="https://user-images.githubusercontent.com/79214262/226292759-6d5150d3-7e4e-4c83-9543-7257b0efa4b5.png">

**Comment by berkersen** [comment]
I did create a project token but I don't have the restrictions you have. Mine looks like this:

![Screen Shot 2023-03-20 at 10 05 35 AM](https://user-images.githubusercontent.com/39887690/226293858-2c6b94ec-1c5a-4489-be49-1522a6cfbc07.png)

**Comment by berkersen** [comment]
I created a new Team named "Languages" with All Languages selected with out any Role selected and selected that one with the token but still doesn't work.

**Comment by berkersen** [comment]
API root url was wrong: https://translate.codeberg.org/api/
 but getting a bunch of other dio errors now: 

`
.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'
E/flutter (20121): #0      PersistedRequest.parseDioErrorMessage (package:weblate_sdk/src/client/request/persisted_request.dart:41:74)
E/flutter (20121): #1      ComponentRequest.getRemote (package:weblate_sdk/src/client/request/component_request.dart:46:28)
E/flutter (20121): <asynchronous suspension>
E/flutter (20121): #2      ComponentRequest.call (package:weblate_sdk/src/client/request/component_request.dart:23:18)
E/flutter (20121): <asynchronous suspension>
E/flutter (20121): #3      WebLateClient._getRemoteTranslations (package:weblate_sdk/src/client/weblate_client.dart:114:27)
E/flutter (20121): <asynchronous suspension>
E/flutter (20121): #4      WebLateSdk.initialize (package:weblate_sdk/src/web_late_sdk.dart:73:21)
`

**Comment by berkersen** [comment]
![Screen Shot 2023-03-20 at 10 32 29 AM](https://user-images.githubusercontent.com/39887690/226300071-333bc068-f86a-4c56-a6f9-31fa666b56c6.png)

**Comment by berkersen** [comment]
This is the token if you wanna debug: wlp_3VWyWAEWJodcM0h8H6a9LuetXWgXUztX3eKm

**Comment by berkersen** [comment]
![Screen Shot 2023-03-20 at 10 42 29 AM](https://user-images.githubusercontent.com/39887690/226302427-6f25f0a6-eacb-4455-9aff-2f6813248b78.png)

**Comment by cozvtieg9** [comment]
Thanks a lot for help. I found an issue in data parsing. (There no currently support for a nested objects, like `"@view_profile": {},` so there was a parser issue). I'll add support of nested objects in future. 

For now I added a fix to parser, and it will available since version 0.0.10.

Also here is your initialization code that works:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/79214262/226303883-a360332b-67b1-4843-b358-e84a5db63a96.png">

**Comment by OnixFlutterTeam** [comment]
I uploaded v 0.0.10, it will available soon.
Please check will it work on new version.
Thanks.
<img width="381" alt="зображення" src="https://user-images.githubusercontent.com/97526574/226305811-c7d1a077-ecee-44ce-bb6e-b7f50527b4ad.png">

**Comment by berkersen** [comment]
Thanks a lot mate, looking forward to the new version. 
One more question: Is there a way to get the translations without the context ? I would love to be able to initialize is with getIt and reach the translations anywhere..
Any suggestions ?

**Comment by cozvtieg9** [comment]
I uploaded v 0.0.10, it will available soon.
Please check will it work on new version.
Thanks.

Currently there no way to get translations without context. Context used to get current phone language Code. 

<img width="381" alt="image" src="https://user-images.githubusercontent.com/79214262/226306042-60cc6aec-920c-4e57-86c6-501dca7ee58c.png">

**Comment by OnixFlutterTeam** [comment]
> Thanks a lot for help. I found an issue in data parsing. (There no currently support for a nested objects, like `"@view_profile": {},` so there was a parser issue). I'll add support of nested objects in future.
> 
> For now I added a fix to parser, and it will available since version 0.0.10.
> 
> Also here is your initialization code that works: <img alt="image" width="497" src="https://user-images.githubusercontent.com/79214262/226303883-a360332b-67b1-4843-b358-e84a5db63a96.png">
also there set disableCache: false if you need caching.. I set it to true only for test purposes.

**Comment by cozvtieg9** [comment]
> Thanks a lot for help. I found an issue in data parsing. (There no currently support for a nested objects, like `"@view_profile": {},` so there was a parser issue). I'll add support of nested objects in future.
> 
> For now I added a fix to parser, and it will available since version 0.0.10.
> 
> Also here is your initialization code that works: <img alt="image" width="497" src="https://user-images.githubusercontent.com/79214262/226303883-a360332b-67b1-4843-b358-e84a5db63a96.png">

**also there set disableCache: false if you need caching.. I set it to true only for test purposes.**

**Comment by berkersen** [comment]
There was a slash at the end of my codes host URL: https://translate.codeberg.org
Removed it and it works now. Thanks mate.
