### ISSUE TITLE
Is string formatting possible ?

### ISSUE THREAD

**Issue by berkersen** [cozvtieg9/weblatesdk#13]
Hi again,

is string formatting possible with the SDK?
Lets say we have such a string in weblate: app_greeting: "Hi {name}!"
Is it possible to format it like context.localizedValueOf('app_greeting', 'Robert'); which will replace the name with Robert ?

**Comment by cozvtieg9** [comment]
Hi. 
Currently not. Planning too add in new version.

**Comment by berkersen** [comment]
This would be a crucial feature. Looking forward to it. Thanks mate.

**Comment by berkersen** [comment]
Wow mate! That was fast! Thanks, looking forward to trying this out! Does it work with multiple strings as well ?
Like,
Usage:
`context.localizedValueOf('app_greeting', format: ['Robert', 'John']);`
Result:
`Hi Robert and John!`

**Comment by cozvtieg9** [comment]
Yes. You can use multiple formatting. 
Just set string as `Hi {name1} and {name2}!`

**Comment by berkersen** [comment]
Just tried it and it works perfectly. Thanks mate!

**Comment by berkersen** [comment]
I'm working on a blog post about your package. Do you have a mastodon or twitter account ?

**Comment by cozvtieg9** [comment]
Thanks! 
No, I don't have those accounts

**Comment by berkersen** [comment]
Ok, I'll just mention your git profile than. Thanks.
